kind: pipeline
name: default

steps:
- name: build-site
  image: node
  commands:
  - npm install
  - npm run build

- name: push-registry
  image: plugins/docker
  settings:
    repo: registry.glidingthrough.space/pascal-riesinger.de
    registry: registry.glidingthrough.space
    tags:
      - latest
      - ${DRONE_TAG}
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
  when:
    branch:
- master
