---
kind: pipeline
name: default
type: docker

steps:
- name: build
  image: plugins/docker
  settings:
    target: builder
    purge: true
    dry_run: true

- name: publish
  image: plugins/docker
  settings:
    repo: reg.infra.riesinger.dev/website
    registry: reg.infra.riesinger.dev
    auto_tag: true
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
  when:
    event: tag

- name: update-service
  image: appropriate/curl
  commands:
  - curl -X POST https://portainer.infra.riesinger.dev/api/webhooks/8c2312e6-7602-4e8a-a8df-ebe6448192b1
  when:
    event: tag
