kind: pipeline
name: default

steps:
- name: build
  image: docker
  commands:
    - docker build -t reg.infra.riesinger.dev/website:dev-$DRONE_COMMIT --target=builder .
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

- name: publish
  image: plugins/docker
  settings:
    repo: reg.infra.riesinger.dev/website
    registry: reg.infra.riesinger.dev
    tags:
      - latest
      - ${DRONE_TAG}
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
  when:
    event: tag

- name: update-service
  image: appropriate/curl
  commands:
    - curl -X POST https://portainer.infra.riesinger.dev/api/webhooks/8c2312e6-7602-4e8a-a8df-ebe6448192b1
  when:
    event: tag
