kind: pipeline
name: default

steps:
- name: build-site
  image: node
  commands:
  - npm install
  - npm run build

- name: push-registry
  image: plugins/docker
  settings:
    repo: registry.glidingthrough.space/pascal-riesinger.de
    registry: registry.glidingthrough.space
    tags:
      - latest
      - ci-${DRONE_BUILD_NUMBER}
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
  when:
    branch:
      - master

- name: deploy-image
  image: quay.io/riesinger/drone-kubernetes:latest
  settings:
    kubernetes_server:
      from_secret: kubernetes_apiserver
    kubernetes_token:
      from_secret: kubernetes_token
    kubernetes_cert:
      from_secret: kubernetes_cert
    kubernetes_user: drone-pascal-deployments
    namespace: pascal
    deployment: pascal-riesinger-de
    container: pascal-riesinger-de
    repo: registry.glidingthrough.space/pascal-riesinger-de
    tag: ci-${DRONE_BUILD_NUMBER}
  when:
    branch:
      - master

