kind: pipeline
name: default

steps:
- name: build-site
  image: node
  commands:
  - npm install
  - npm run build

- name: push-registry
  image: plugins/docker
  settings:
    repo: registry.glidingthrough.space/pascal-riesinger.de
    registry: registry.glidingthrough.space
    tags:
      - latest
      - ${DRONE_TAG}
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
  when:
    event:
      - tag

- name: deploy-image
  image: quay.io/honestbee/drone-kubernetes
  settings:
    kubernetes_server:
      from_secret: kubernetes_apiserver
    kubernetes_token:
      from_secret: kubernetes_token
    namespace: pascal
    deployment: pascal-riesinger-de
    repo: registry.glidingthrough.space/pascal-riesinger-de
    tag: ${DRONE_TAG}
  when:
    event:
      - tag

