name = "riesinger"
license = "MIT"
licenselink = "https://github.com/riesinger/riesinger-hugo-theme/blob/master/LICENSE.md"
description = "A clean light & dark blog theme for Hugo"
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.30

[author]
  name = "Pascal Riesinger"
  homepage = "https://riesinger.dev"
  twitter = "https://twitter.com/pascalriesinger"
